[project]
name = "stock-exchange-dump"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "hence>=0.12.1",
    "pandas>=2.2.3",
    "parsel>=1.10.0",
    "typing-extensions>=4.13.0",
]

[dependency-groups]
dev = [
    "ruff>=0.11.5",
]
