name: Collect daily dump

on:
  workflow_dispatch: ~

jobs:
  collect_dump:
    name: Collect daily dump for latest share price from DSEBD.ORG
    runs-on: ubuntu-22.04

    steps:
      - name: Get the code from master branch
        uses: actions/checkout@v4
        with:
          ref: 'ci/daily-dump-01'
          path: 'master-br'

      - name: Set up Python 3.11.6
        uses: actions/setup-python@v5
        with:
            python-version: '3.11.6'
            cache: 'pip'

      - name: Set up Python packages
        run: |
          cd ./master-br
          pip install -r requirements.txt

      - name: Fetch and parse the page, then update the added_file path
        id: outdata
        run: |
          cd ./master-br
          bash scripts/fetchSharePrice.sh
          echo "added_file=$(pwd)/$(git ls-files --others --exclude-standard)" >> $GITHUB_OUTPUT
          ls -lah ./dumps/dse/share_price/

      - name: Commit newly added file ${{ steps.outdata.outputs.added_file }} to dump-files branch
        run: |
          cd ./master-br
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add DSE stock price for $(date +'%Y-%m-%d')"
        if: ${{ endsWith(steps.outdata.outputs.added_file, '.csv') }}

      - name: GitHub Push to dump-files branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          directory: master
        if: ${{ endsWith(steps.outdata.outputs.added_file, '.csv') }}
