name: Collect daily dump

on:
  workflow_dispatch: ~

jobs:
  collect_dump:
    name: Collect daily dump for latest share price from DSEBD.ORG
    runs-on: ubuntu-22.04

    steps:
      - name: Get the code from master branch
        uses: actions/checkout@v4
        with:
          ref: 'ci/daily-dump-01'

      - name: Set up Python 3.11.6
        uses: actions/setup-python@v5
        with:
            python-version: '3.11.6'
            cache: 'pip'

      - name: Set up Python packages
        run: pip install -r requirements.txt

      - name: Fetch and parse the page, then update the added_file path
        id: outdata
        run: |
          bash scripts/fetchSharePrice.sh
          echo "added_file=$(git ls-files --others --exclude-standard)" >> $GITHUB_OUTPUT
          echo "commit_msg=Add DSE stock price for $(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "pr_branch=dump-files/dse-stock-price-$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # - name: Commit newly added file ${{ steps.outdata.outputs.added_file }}
      #   id: prbranch
      #   run: |
      #     git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
      #     git config --local user.name "github-actions[bot]"
      #     BRANCH="dump-files/dse-stock-price-$(date +'%Y-%m-%d')"
      #     git checkout -b $BRANCH
      #     git add .
      #     git commit -u -m "Add DSE stock price for $(date +'%Y-%m-%d')"
      #     echo "pr_branch=$BRANCH" >> $GITHUB_OUTPUT
          
      #   if: ${{ endsWith(steps.outdata.outputs.added_file, '.csv') }}

      # - name: GitHub push file ${{ steps.outdata.outputs.added_file }} to ${{ steps.prbranch.outputs.pr_branch }}
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.PAT_0HSN }}
      #     branch: ${{ steps.prbranch.outputs.pr_branch }}
      #   if: ${{ endsWith(steps.outdata.outputs.added_file, '.csv') }}
      
      - name: Push file ${{ steps.outdata.outputs.added_file }}
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          fetch: false
          message: ${{ steps.prbranch.outputs.commit_msg }}
          new_branch: ${{ steps.prbranch.outputs.pr_branch }}
        
        if: ${{ endsWith(steps.outdata.outputs.added_file, '.csv') }}

