name: Collect daily dump

on:
  workflow_dispatch: ~

jobs:
  collect_dump:
    name: Collect daily dump for latest share price from DSEBD.ORG
    runs-on: ubuntu-22.04

    env:
      DT_TODY: ""

      # BR_CODE: "master"
      BR_CODE: "ci/daily-dump-01"
      BR_DUMP: "dump-files"
      BR_DUMP_PR: "dump-files/dse-stock-price"

      FL_DUMP: ""

      PT_CODE: "ci-daily-dump-01"
      PT_DUMP: "dump-files"

      COMMIT_MSG: "Add DSE stock price on date"

    steps:
      - name: Dynamically set MY_DATE environment variable
        run: echo "DT_TODY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # - name: Get the code from code branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ env.BR_DUMP }}
      #     # token: ''
      #     path: ${{ env.PT_DUMP }}

      - name: Set up Python 3.11.7
        uses: actions/setup-python@v5
        with:
            python-version: '3.11.7'
            cache: 'pip'

      - name: Set up Python packages
        run: |
          cd $PT_CODE
          pip install -r requirements.txt

      - name: Fetch and parse the page, then update the added_file path
        run: |
          cd $PT_CODE
          bash scripts/fetchSharePrice.sh
          git status -u
          echo $(git ls-files --others --exclude-standard)
          echo "FL_DUMP=$(git ls-files --others --exclude-standard)" >> $GITHUB_OUTPUT

      # - name: Get the code from file dump branch
      #   uses: actions/checkout@v4
      #   with:
      #     ref: ${{ env.BR_DUMP }}
      #     # token: ''
      #     path: ${{ env.PT_DUMP }}
  
      - name: Copy create dump to dump path
        run: |
          # cp "${{ env.PT_CODE }}/${{ env.FL_DUMP }}" "${{ env.PT_DUMP }}/$(dirname ${{ env.FL_DUMP }})"

          echo $PT_CODE/$FL_DUMP
          echo $PT_DUMP/$(dirname $FL_DUMP)

      # - name: Push file ${{ env.FL_DUMP }}
      #   uses: EndBug/add-and-commit@v9
      #   if: ${{ endsWith(env.FL_DUMP, '.csv') }}
      #   with:
      #     default_author: github_actions
      #     fetch: false
      #     message: ${{ env.COMMIT_MSG }} ${{ env.DT_TODY }}
      #     new_branch: ${{ env.BR_DUMP_PR }}-${{ env.DT_TODY }}
