name: Collect daily dump

on:
  workflow_dispatch: ~

jobs:
  collect_dump:
    name: Collect daily dump for latest share price form DSEBD
    runs-on: ubuntu-22.04
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"


