name: Dump daily - DSE - Stock price

on:
  workflow_dispatch: ~
  schedule:
    - cron: "0 10 * * 0-4"

jobs:
  collect_dump:
    name: Collect daily dump for latest share price from DSEBD.ORG
    runs-on: ubuntu-22.04

    env:
      DT_TODY: ""

      BR_DUMP: "master"
      BR_DUMP_PR: "new-files/dse-stock-price"

      FL_DUMP: ""

      COMMIT_MSG: "Add DSE stock price on date"

      DSE_STOCK_PRICE_PAGE: "https://www.dsebd.org/latest_share_price_scroll_l.php"
      CMD_STOCK_PRICE_PAGE: "python -m sed_parser --site dse --page-type sharePrice --format csv"

    steps:
      - name: Dynamically set MY_DATE environment variable
        run: |
          echo "DT_TODY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo $(date +'%Y-%m-%d')

      - name: Get the code from code branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_PAT }}

      - name: Set up Python 3.11.7
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.7"
          cache: "pip"

      - name: Set up Python packages
        run: pip install -r requirements.txt

      - name: Fetch and parse the page, then update the `FL_DUMP` path
        run: |
          curl ${{ env.DSE_STOCK_PRICE_PAGE }} -s | ${{ env.CMD_STOCK_PRICE_PAGE }}
          echo "FL_DUMP=$(git ls-files --others --exclude-standard)" >> $GITHUB_ENV
          git status -u

      - name: Push file `${{ env.FL_DUMP }}`
        id: pushout
        uses: EndBug/add-and-commit@v9
        if: ${{ endsWith(env.FL_DUMP, '.csv') }}
        with:
          default_author: github_actions
          fetch: false
          message: ${{ env.COMMIT_MSG }} ${{ env.DT_TODY }}
          new_branch: ${{ env.BR_DUMP_PR }}-${{ env.DT_TODY }}

      - name: Create PR to `${{env.BR_DUMP}}`
        if: ${{ steps.pushout.outputs.pushed == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.CI_PAT }}
        run: |
          gh pr create -B ${{env.BR_DUMP}} -H "${{ env.BR_DUMP_PR }}-${{ env.DT_TODY }}" -f
